simulation:
  simulator: matlab
  type: streaming
  name: SimulazioneDinamicaAgenti
  path: /Users/marcomelloni/Desktop/AU_University/simulation-bridge/agents/MATLABagent_tcp_v1
  file: Simulation.m
  inputs:
    num_agents: 2 # Numero di agenti
    max_steps: 1000 # Numero massimo di passi
    avoidance_threshold: 2 # Distanza minima di separazione tra gli agenti
    show_agent_index: 1 # Indice dell'agente da visualizzare
    use_gui: false # Abilita o disabilita la GUI
  # outputs:
  #   time: float # Tempo simulato in secondi
  #   current_step: int # Passo corrente
  #   positions: "[[float, float]]" # Lista di posizioni per ogni agente
  #   velocities: "[[float, float]]" # Lista di velocità per ogni agente
  #   running: bool # Flag che indica se la simulazione è in corso
