rabbitmq:
  host: "localhost"
  port: 5672
  virtual_host: "/"
  username: "guest"
  password: "guest"
  heartbeat: 60
  blocked_connection_timeout: 300
  ssl: false
  ssl_cafile: "/path/to/ca.pem"
  ssl_certfile: "/path/to/client_cert.pem"
  ssl_keyfile: "/path/to/client_key.pem"
queues:
  request: "queue_simulation"
  response: "queue_response"
  data: "agent_updates"
