# simulation:
#   matlab_function: "SimulationAgents" # Nome della funzione MATLAB da chiamare
#   input_size: 10 # Numero di input
#   output_size: 5 # Numero di output
#   input_data: # Dati di input, che potrebbero essere una lista o qualsiasi altro tipo
#     - 1.0
#     - 0.5
#     - 0.2
#     - 0.8
#     - 1.5
#     # Aggiungere qui altre variabili di input se necessario
#   stop_condition:
#     type: "threshold" # Tipo di condizione di stop (e.g., "threshold", "time")
#     value: 1000 # Soglia per la condizione di stop
#   output_names:
#     - "position_1"
#     - "position_2"
#     - "position_3"
#     - "position_4"
#     - "position_5"
#   shared_memory_file: "shared_memory.bin" # Nome del file di memoria condivisa (opzionale)

simulation:
  matlab_function: "Simulation" # Nome della funzione MATLAB da chiamare
  input_size: 1 # Un solo valore di input (velocità)
  output_size: 5 # La simulazione restituisce 5 elementi (1 posizione + 4 zeri)
  input_data: # Dati di input (un valore di velocità)
    - 1.0
  stop_condition:
    type: "threshold" # Tipo di condizione di stop
    value: 1000 # La posizione deve raggiungere o superare 1000
  output_names:
    - "position_1"
  shared_memory_file: "shared_memory.bin" # Nome del file di memoria condivisa
